# Generated by Django 5.0.2 on 2024-02-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
